version: '3.9'

services:
  wordpress:
    build:
      context: .
      dockerfile_inline: |
        FROM wordpress:latest

        # Install necessary dependencies
        RUN apt-get update && apt-get install -y \
            libzip-dev \
            unzip \
            git \
            && rm -rf /var/lib/apt/lists/*

        # Install phpredis extension
        RUN pecl install redis \ 
            && docker-php-ext-enable redis

    volumes:
      - wordpress-files:/var/www/html
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${SERVICE_USER_WORDPRESS}
      - WORDPRESS_DB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS}
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_REDIS_HOST', 'redis');define('WP_REDIS_PORT', 6379);define('WP_CACHE', true);
    depends_on:
      - mariadb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10

  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=${SERVICE_USER_WORDPRESS}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_WORDPRESS}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 5s
      timeout: 10s
      retries: 20

volumes:
  wordpress-files:
  mariadb-data:
  redis-data:
